language: minimal
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - curl
      - openssl
      - ca-certificates
      - make
      - qemu-user-static
env:
  global:
    - DOCKER_BUILDKIT=0
  matrix:
    - DISTRIB_ID=ubuntu VARIANT=minsize   MARCH=arm32v7  CHECK_TARGET=check
    - DISTRIB_ID=ubuntu VARIANT=minsize   MARCH=arm32v7  CHECK_TARGET=check
    - DISTRIB_ID=ubuntu VARIANT=debug     MARCH=arm32v7  CHECK_TARGET=check
    - DISTRIB_ID=ubuntu VARIANT=release   MARCH=arm32v7  CHECK_TARGET=check
    - DISTRIB_ID=ubuntu VARIANT=release   MARCH=arm32v7  CHECK_TARGET=check
before_script:
- make -j4 DISTRIB_ID=$DISTRIB_ID VARIANT=$VARIANT MARCH=$MARCH
script:
- make -j1 DISTRIB_ID=$DISTRIB_ID VARIANT=$VARIANT MARCH=$MARCH $CHECK_TARGET
after_success:
- bash <(curl -s https://codecov.io/bash)
